### ISSUE TITLE
NPM install throws error

### ISSUE THREAD

**Issue by alaaabouzeid** [mapbox/directions-icons#10]
Hi thanks for the awesome icons! I was trying to generate a new set of icons in a different color and I followed the instructions in the readme but I got the following errors when running npm install command. Can you please help? Thanks a lot.

C:\GitHub Projects\directions-icons>npm install
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.

> mapnik@3.7.2 install C:\GitHub Projects\directions-icons\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-win32-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-win32-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\lib\\binding\\mapnik.node" "--module_name=mapnik" "--module_path=C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\lib\\binding"
gyp ERR! cwd C:\GitHub Projects\directions-icons\node_modules\mapnik
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\GitHub Projects\directions-icons\node_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\GitHub Projects\directions-icons\node_modules\mapnik
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding' (1)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alaa\AppData\Roaming\npm-cache\_logs\2019-04-01T19_46_16_026Z-debug.log

**Comment by andrewharvey** [comment]
you can install a newer version of mapnik into the package.json

**Comment by alaaabouzeid** [comment]
@andrewharvey  thanks for your response. I'm afraid I'm not very good with mapnik so I'm not sure what to do here. Can you please provide more guidance or instructions? Thanks a lot :)

**Comment by andrewharvey** [comment]
`yarn add --dev mapnik` inside the directory where the package.json is.

I'm not sure what the --dev equivalent for npm is.

**Comment by alaaabouzeid** [comment]
thanks for getting back to me. sorry to be a pain but it is still not working :( I installed yarn and ran the command yarn add --dev mapnik and I got the following output:
C:\GitHub Projects\directions-icons>yarn add --dev mapnik
yarn add v1.15.2
info No lockfile found.
[1/4] Resolving packages...
warning mapbox.js > sanitize-caja@0.1.3: This module is now under the @mapbox namespace: install @mapbox/sanitize-caja instead
warning mapbox.js > corslite@0.0.6: This module is now under the @mapbox namespace: install @mapbox/corslite instead
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\GitHub Projects\directions-icons\node_modules\mapnik: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\GitHub Projects\directions-icons\node_modules\mapnik
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@10.15.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.2.1/node-v64-win32-x64-Release.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.2.1/node-v64-win32-x64-Release.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.2.1/node-v64-win32-x64-Release.tar.gz
node-pre-gyp WARN Pre-built binaries not found for mapnik@4.2.1 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.2.1/node-v64-win32-x64-Release.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.2.1 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file

C:\GitHub Projects\directions-icons\node_modules\mapnik>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\GitHub Projects\directions-icons\node_modules\mapnik>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp info ok
gyp info ok

C:\GitHub Projects\directions-icons\node_modules\mapnik>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node" --module_name=mapnik "--module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding" --napi_version=3 --node_abi_napi=napi )  else (node "" configure --fallback-to-build "--module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node" --module_name=mapnik "--module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding" --napi_version=3 --node_abi_napi=napi )

C:\GitHub Projects\directions-icons\node_modules\mapnik>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node" --module_name=mapnik "--module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding" --napi_version=3 --node_abi_napi=napi )  else (node "" configure --fallback-to-build "--module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node" --module_name=mapnik "--module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding" --napi_version=3 --node_abi_napi=napi )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\lib\\binding\\mapnik.node" "--module_name=mapnik" "--module_path=C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\GitHub Projects\directions-icons\node_modules\mapnik
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\lib\\binding\\mapnik.node" "--module_name=mapnik" "--module_path=C:\\GitHub Projects\\directions-icons\\node_modules\\mapnik\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\GitHub Projects\directions-icons\node_modules\mapnik
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\GitHub Projects\directions-icons\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\GitHub Projects\\directions-icons\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\GitHub Projects\directions-icons\node_modules\mapnik
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=C:\GitHub Projects\directions-icons\node_modules\mapnik\lib\binding --napi_version=3 --node_abi_napi=napi' (1)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by andrewharvey** [comment]
See the windows specific information at https://github.com/mapnik/node-mapnik#installing

Sorry I've only ever done this on Linux, so can't comment on Windows specific issues.

**Comment by alaaabouzeid** [comment]
this is proving to be quite a pain.. so many errors and stuff that are out of support :(
probably easier if I sent you a new hex color and you can generate the icons for that, pretty please?

**Comment by andrewharvey** [comment]
According to https://github.com/mapnik/node-mapnik#installing "After 3.6.2 no Windows binaries are provided." so you'd either need to do the source build of mapnik, or try on a supported linux platform.

**Comment by alaaabouzeid** [comment]
thanks for that i'll try to have a look at this.
